spring:
  application:
    name: test-server
  graphql:
    websocket:
      path: /graphql
      connection-init-timeout: 10s
    graphiql:
      enabled: true
      path: /graphiql
  webflux:
    multipart:
      max-parts: -1
      max-disk-usage-per-part: -1

server:
  port: 18081
  http2:
    enabled: true

grpc:
  server:
    port: 18082

logging:
  level:
    com.sunnychung: DEBUG
    io.netty: DEBUG
    _reactor.netty.channel.LeakDetection: DEBUG
