name: Hello HTTP Github CI/CD
on:
  push:
    tags:
      - v**
jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew createDistributable packageDistributionForCurrentOS
      - run: pushd ./build/compose/binaries/main/app && ls -al && tar -cvzf "app.tar.gz" "Hello HTTP" && mv "app.tar.gz" "../../../../../HelloHTTP-${{ github.ref.name }}-ubuntu-${{ runner.arch }}.tar.gz" && popd
      - uses: softprops/action-gh-release@v1
        with:
          files: "HelloHTTP-${{ github.ref.name }}-ubuntu-${{ runner.arch }}.tar.gz"
