name: Hello HTTP Github CI/CD
on:
  push:
    tags:
      - v**
permissions:
  contents: write
  actions: read
  checks: read
  deployments: read
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: none
  statuses: read
jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./github/workflows/build-jetpack-compose-app.yaml
      - run: pushd ./build/compose/binaries/main/app && ls -al && tar -cvzf "app.tar.gz" "Hello HTTP" && mv "app.tar.gz" "../../../../../HelloHTTP-${{ github.ref_name }}-ubuntu-${{ runner.arch }}.tar.gz" && popd
      - uses: softprops/action-gh-release@v1
        with:
          files: "HelloHTTP-${{ github.ref_name }}-ubuntu-${{ runner.arch }}.tar.gz"
