name: Verification Tests
on:
  push:
    branches:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: |
          ./gradlew bootRun &
          READY=false
          for attempt in {1..20}; do sleep 1; if curl -sI --fail-early -f http://localhost:18081/actuator/health/; then READY=true; break; fi; echo "Waiting for Test Server to be UP"; done
          [ "$READY" = true ] || (echo "Test Server is not UP" && exit 1)
          echo "Test Server is UP"
          ./gradlew check -PisCI=true
